// Package sync pulls the palettes out of the lvim-gtk repository on GitHub
// and writes them as inline themes into ~/.config/themer/themes.toml.
//
// The generated file is separate from config.toml on purpose: sync
// regenerates themes.toml wholesale, and a hand-written config must never
// be on the losing side of that. config.toml's own [[themes]] load after
// the synced ones, so a manual definition still overrides by name.
package sync

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/lvim-tech/themer/internal/theme"
)

// entry is the slice of the GitHub contents API response sync needs.
type entry struct {
	Name        string `json:"name"`
	DownloadURL string `json:"download_url"`
}

// Run fetches every palette of repo (owner/name) and writes dest. apiBase
// is "https://api.github.com" outside of tests. Returns how many themes
// landed.
func Run(apiBase, repo, dest string) (int, error) {
	client := &http.Client{Timeout: 30 * time.Second}

	url := fmt.Sprintf("%s/repos/%s/contents/palettes", apiBase, repo)
	body, err := get(client, url)
	if err != nil {
		return 0, err
	}
	var entries []entry
	if err := json.Unmarshal(body, &entries); err != nil {
		return 0, fmt.Errorf("%s did not return a directory listing: %w", url, err)
	}

	type def struct {
		name    string
		palette theme.Palette
	}
	var defs []def
	for _, e := range entries {
		base, ok := strings.CutSuffix(e.Name, ".scss")
		if !ok {
			continue
		}
		name, ok := theme.NameFor(base)
		if !ok {
			continue
		}
		raw, err := get(client, e.DownloadURL)
		if err != nil {
			return 0, err
		}
		p, err := theme.ParsePalette(strings.NewReader(string(raw)), e.Name)
		if err != nil {
			return 0, err
		}
		defs = append(defs, def{name: name, palette: p})
	}
	if len(defs) == 0 {
		return 0, fmt.Errorf("no palettes found in %s", repo)
	}
	sort.Slice(defs, func(i, j int) bool { return defs[i].name < defs[j].name })

	var b strings.Builder
	fmt.Fprintf(&b, "# GENERATED by `themer --sync` from github.com/%s on %s.\n", repo, time.Now().Format("2006-01-02"))
	b.WriteString("# Every sync rewrites this file — hand edits belong in config.toml,\n")
	b.WriteString("# whose [[themes]] override these by name.\n")
	for _, d := range defs {
		fmt.Fprintf(&b, "\n[[themes]]\nname = %q\n\n[themes.palette]\n", d.name)
		keys := make([]string, 0, len(d.palette))
		width := 0
		for k := range d.palette {
			keys = append(keys, k)
			if len(k) > width {
				width = len(k)
			}
		}
		sort.Strings(keys)
		for _, k := range keys {
			fmt.Fprintf(&b, "%-*s = %q\n", width, k, d.palette[k])
		}
	}

	// Write-then-rename: a sync that dies mid-write must not leave a
	// truncated themes.toml that silently halves the theme list.
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return 0, err
	}
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o644); err != nil {
		return 0, err
	}
	if err := os.Rename(tmp, dest); err != nil {
		return 0, err
	}
	return len(defs), nil
}

func get(client *http.Client, url string) ([]byte, error) {
	resp, err := client.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}
	return io.ReadAll(resp.Body)
}
